### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wtrocki** [aerogear/datasync#229]
## Roadmap for DataSync 1.0

DataSync 1.0 will focus on aggregating all libraries available in the ecosystem to work together in form of fully functional examples and boilerplates. Together with Offix and Graphback we can provide end to end data synchronization system

### Tasks

- [ ] DataSync boilerplate #233 
- [ ] Subscriptions with diff capabilities #232 
- [ ] Integration with Graphback #231 
- [ ] Documentation and website refinement
